### ISSUE TITLE
Document an example GitHub Actions workflow run failure with ESLint errors

### ISSUE THREAD

**Issue by jaydenseric** [sjinks/eslint-gha-formatter#145]
Hi! This project looks like a really interesting idea. The general point is understandable, that if it's a GitHub actions environment the ESLint CLI output will be in a way GitHub Actions can present nicer, but what does this actually look like? It's hard to imagine. I tried searching the workflow runs in this repo for one that failed due to ESLint errors to see what it looks like, but it seems there are none.

Maybe you could raise (and then close) a demo PR that has purposefully a lot of lint errors showcasing what the ESLint report looks like in the GitHub Actions workflow run UI, and then add a link to that failed run in the readme. I'm not sure how long GitHub keeps failed run output around though. Maybe when it gets purged you can just re-run the workflow?

Alternatively, you could add a screenshot to readme of what the annotated output in GitHub Actions UI looks like, but then anytime GitHub changes the UI the screenshot won't reflect reality and we won't be able to try out any of the UI interactivity.

**Comment by sjinks** [comment]
@jaydenseric here are the sample screenshots:

![failed-validation-1](https://user-images.githubusercontent.com/7810770/144342984-e10b35a7-bab8-4994-87bf-f21934e0efbb.png)
![failed-validation-2](https://user-images.githubusercontent.com/7810770/144342990-0815938f-2d45-4b9f-8a69-5401e864044a.png)
![failed-validation-3](https://user-images.githubusercontent.com/7810770/144342994-6f4cb8ea-60d8-4147-b806-e9a3b696be30.png)

This is the [failed run](https://github.com/sjinks/eslint-gha-formatter/actions/runs/1528652431); I think GitHub will kill the logs after some time.
